hw/xen/xen_pt: Add missing error-report include
Fixes the following compilation error:

  ../src/hw/xen/xen_pt.c: In function ‘xen_pt_need_gsi’:
  ../src/hw/xen/xen_pt.c:783:9: error: implicit declaration of function ‘error_report’; did you mean ‘error_report_err’? [-Wimplicit-function-declaration]
    783 |         error_report("Cannot open %s: %s", guest_type, strerror(errno));
        |         ^~~~~~~~~~~~
        |         error_report_err
  ../src/hw/xen/xen_pt.c:783:9: error: nested extern declaration of ‘error_report’ [-Werror=nested-externs]

Fixes: 012842c07552 ("log: make '-msg timestamp=on' apply to all qemu_log usage")
Signed-off-by: Bernhard Beschow <shentey@gmail.com>